[package]
name = "nib"
version = "0.1.0"
authors = ["Afnan Enayet <afnan@afnan.io>"]
edition = "2018"

[dependencies]
num = "0.2.0"
cgmath = { version = "0.17.0", features = ["serde"] }
structopt = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.6"
rand = { version = "0.7", features = ["log", "serde1"] }
image = "0.22.3"
typetag = "0.1"
